camunda:
  bpm:
    admin-user:
      id: demo
      password: demo
    filter:
      create: All Tasks
    authorization:
      enabled: false

spring:
  profiles:
    active: local
#  jersey:
#    application-path: /rest
#  datasource:
#    url: jdbc:h2:file:./data/camunda
#    username: sa
#    password: sa
## Uncomment the following lines to enable the h2 DB console:
#  h2:
#    console:
#      enabled: true
#      path: /console

## Uncomment the following lines to change to port number:
#server:
#  port: 8081