camunda:
  bpm:
    admin-user:
      id: demo
      password: demo

# This is for using a file-based DB
# In this case the Camunda data/configuration will persist
# The file will be placed user the users directory
#
#spring:
#  datasource:
#    url: jdbc:h2:file:~/camunda
#    username: sa
#    password: sa

#spring:
#  h2:
#    console:
#      enabled: true
#      path: /console

# This is for using a remote MySQL/Maria DB
# In Jelastic you may need a public IPv4
# Don't forget to add the MySQL driver to POM
#
#spring:
#  datasource:
#    url: jdbc:mysql://mariadb40920-digi-bp.appengine.flow.ch:3306/digibp?autoReconnect=true
#    username: digibp
#    password: digibp
#    driverClassName: com.mysql.jdbc.Driver